[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirect root to /bidhub/ 
[[redirects]]
  from = "/"
  to = "/bidhub/"
  status = 301
  force = true

# SPA fallback for all /bidhub/* routes
[[redirects]]
  from = "/bidhub/*"
  to = "/bidhub/index.html"
  status = 200