[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirect root to /bidhub/
[[redirects]]
  from = "/"
  to = "/bidhub/"
  status = 301
  force = true

# Redirect /bidhub (without trailing slash) to /bidhub/
[[redirects]]
  from = "/bidhub"
  to = "/bidhub/"
  status = 301
  force = true

# SPA fallback - ALL /bidhub/* routes go to root index.html
[[redirects]]
  from = "/bidhub/*"
  to = "/index.html"
  status = 200