[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL,VITE_CLOUDINARY_CLOUD_NAME,VITE_CLOUDINARY_FOLDER,VITE_CLOUDINARY_UPLOAD_PRESET,VITE_PAYPAL_CLIENT_ID,VITE_PAYPAL_MODE"

# If you need the /bidhub base
[[redirects]]
  from = "/"
  to = "/bidhub/"
  status = 301
  force = true

[[redirects]]
  from = "/bidhub"
  to = "/bidhub/"
  status = 301
  force = true

[[redirects]]
  from = "/bidhub/*"
  to = "/index.html"
  status = 200